spring.application.name=controleFinanceiro

#database config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#jpa settings
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#JWT settings
#JWT_SECRET_KEY=${JWT_SECRET_KEY}
