spring.application.name=controleFinanceiro

#database config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#jpa settings
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#JWT settings
jwt.secret.key=${JWT_SECRET_KEY}
jwt.bearer=${JWT_BEARER}
jwt.authorization=${JWT_AUTHORIZATION}
jwt.expire.days=${JWT_EXPIRE_DAYS}
jwt.expire.hours=${JWT_EXPIRE_HOURS}
jwt.expire.minutes=${JWT_EXPIRE_MINUTES}
